// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package masche.example.greet.v1;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.greet.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  masche.example.greet.v1.Greeting getGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   */
  masche.example.greet.v1.GreetingOrBuilder getGreetingOrBuilder();
}
